### ISSUE TITLE
期待作者分享改进后的代码

### ISSUE THREAD

**Issue by hhrhapsody** [hitzhangyu/V2-Self-supervised-Image-Enhancement-Network-Training-With-Low-Light-Images-Only#4]
感觉改进后的方法提升很大，非常希望能应用到自己的研究中，另外想确认下文章中是否是吧反射图R作为增强图像的？

**Comment by hitzhangyu** [comment]
是的，也可以利用R*I^γ进行进一步的亮度调整

**Comment by hhrhapsody** [comment]
作者你好！
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 我是一名研二的学生，也是在做低照度图像增强方向的，看了你的改进方法论文后想把其中一些东西应用到我自己的毕业论文中，想知道你近期是否有分享代码的打算，以此来规划我自己的实验。
感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hitzhangyu/V2-Self-supervised-Image-Enhancement-Network-Training-With-Low-Light-Images-Only"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 上午10:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hitzhangyu/V2-Self-supervised-Image-Enhancement-Network-Training-With-Low-Light-Images-Only] 期待作者分享改进后的代码 (#4)





 
是的，也可以利用R*I^γ进行进一步的亮度调整

**Comment by hitzhangyu** [comment]
论文已投在等结果，审稿结果好的话6月10号后会把代码公开，不好的话得接着改。可以发信息到我邮箱（hitzhangyu@qq.com），我可以先把最新改进后论文发给你

**Comment by buptlj** [comment]
代码会公开吗，waiting

**Comment by ybb-ybb** [comment]
求问，代码会公开吗

**Comment by Zruto** [comment]
期待代码公开

**Comment by eorroot** [comment]
代码还会公开吗

**Comment by trafalgarlo** [comment]
代码可以公开了吗

**Comment by wwl991122** [comment]
请问代码可以公开了吗？
