### ISSUE TITLE
Missing Important Reference

### ISSUE THREAD

**Issue by yifanjiang19** [hitzhangyu/V2-Self-supervised-Image-Enhancement-Network-Training-With-Low-Light-Images-Only#5]
Hi,

This is work is pretty impressive and I personally very much enjoy reading it. The idea is very novel. However, one important reference [1] is missing as [1] is also developed for label-free training settings. We would like to kindly suggest the author add this one to help the reader have a clearer background of the related topic, as well, the code is also ready [2] for any ustility. Thank!

Best, 

Reference:
[1] EnlightenGAN: Deep Light Enhancement without Paired Supervision.
[2] https://github.com/VITA-Group/EnlightenGAN

**Comment by hitzhangyu** [comment]
Thanks a lot, I have cited this work in my revised  paper. The revised paper can be found in [1]
[1] https://www.researchgate.net/publication/349683113_Self-supervised_Low_Light_Image_Enhancement_and_Denoising

**Comment by yifanjiang19** [comment]
Great! Hope to see more interesting work!
